main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmainpage, name="mainpage"),
    path('main/', showmainpage, name="mainpage"),
    path('introduction/',showintroduction, name="introduction"),
    path('show/',showshow, name="show"),
    path('post/',showpost, name="post"),
    path('<int:id>',detail, name="detail"),
    path('new/', new, name="new"),
    path('create/',create, name="create"),
    path('edit/<int:id>',edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<int:post_id>/create_comment',create_comment,name="create_comment"),
    path('<int:comment_id>/update_comment',update_comment,name="update_comment"),
    path('<int:comment_id>/delete_comment',delete_comment, name="delete_comment"),

    path('like_toggle/<int:post_id>/',like_toggle,name="like_toggle"),
    path('dislike_toggle/<int:post_id>/',dislike_toggle,name="dislike_toggle"),
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .import views

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage',views.mypage, name="mypage"),
    path('<int:id>/follow',views.follow, name="follow"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    followings = models.ManyToManyField("self", related_name="followers", symmetrical=False)

@receiver(post_save, sender = User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main.models import Post
from django.contrib.auth.models import User

# Create your views here.
def mypage(request, id):
    user = get_object_or_404(User, pk = id)
    login_user = request.user
    context = {
        'user':user,
        'login_user':login_user,
        'posts':Post.objects.filter(writer=user),
        'followings':user.profile.followings.all(),
        'followers':user.profile.followers.all(),
    }
    return render(request,'users/mypage.html',context)

def follow(request, id):
    user = request.user
    followed_user = get_object_or_404(User, pk=id)
    is_follower = user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <head>
      <link rel="stylesheet" href="{%static 'css/mypage.css' %}">
    </head>
    <body>
    {% include 'shared/_navbar.html' %}
    <div class = "container">
        <div class='mypage '>
            <img src="{%static 'image/teamwork.png' %}" width="100px" height="100px" style="margin-bottom: 20px;">
            <P>마이페이지</p>
        </div>
        <div>
        {% if user.username == "user" %}
        <h2>{{user.last_name}} {{user.first_name}}</h2>
        {% else %}
        <h2>{{user.username}}</h2>
        {% endif %}
        {% if request.user != user %}
        {% if request.user.profile in user.profile.followers.all %}
        <a href="{% url 'users:follow' user.id %}"><button>언팔로우</button></a>
        {% else %}
        <a href="{% url 'users:follow' user.id %}"><button>팔로우</button></a>
        {% endif %}
        {% endif %}
        </div>
        <span>내가 쓴 글 목록</span>
        <table class="profile" style=" width: 60%;">
            <thead>
            <tr>
              <th scope="cols" width=10%>순번</th>
              <th scope="cols" width=40%>제목</th>
              <th scope="cols" width=35%>날짜</th>
            </tr>
            </thead>
            <tbody>
            {% for post in posts %} 
            <tr onclick="location.href='{% url 'main:detail' post.id %}'">
                <td>{{ forloop.counter }}</td>
                <td>{{ post.title }}</td>
                <td>{{ post.pub_date }}</td>  
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>    
    </body>
    <style>
        table {
    border-collapse: collapse;
    text-align: left;
    line-height: 1.5;
    border-left: 1px solid #ccc;
    margin: auto;
  }
  
  table thead th {
    padding: 10px;
    font-weight: bold;
    border-top: 1px solid #ccc;
    border-right: 1px solid #ccc;
    border-bottom: 2px solid #c00;
    background: #dcdcd1;
  }
  table tbody th {
    width: 150px;
    padding: 10px;
    font-weight: bold;
    vertical-align: top;
    border-right: 1px solid #ccc;
    border-bottom: 1px solid #ccc;
    background: #ececec;
  }
  table td {
    width: 350px;
    padding: 10px;
    vertical-align: top;
    border-right: 1px solid #ccc;
    border-bottom: 1px solid #ccc;
    background: white;
  }
    </style>
{% endblock %}