main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmainpage, name="mainpage"),
    path('main/', showmainpage, name="mainpage"),
    path('introduction/',showintroduction, name="introduction"),
    path('show/',showshow, name="show"),
    path('post/',showpost, name="post"),
    path('<int:id>',detail, name="detail"),
    path('new/', new, name="new"),
    path('create/',create, name="create"),
    path('edit/<int:id>',edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<int:post_id>/create_comment',create_comment,name="create_comment"),
    path('<int:comment_id>/update_comment',update_comment,name="update_comment"),
    path('<int:comment_id>/delete_comment',delete_comment, name="delete_comment"),

    path('like_toggle/<int:post_id>/',like_toggle,name="like_toggle"),
    path('dislike_toggle/<int:post_id>/',dislike_toggle,name="dislike_toggle"),
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .import views

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage',views.mypage, name="mypage"),
    path('<int:id>/follow',views.follow, name="follow"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "posts/", blank=True, null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='likes_user_set',through='Like')
    dislike_user_set = models.ManyToManyField(User, blank=True, related_name='dislikes_user_set',through='Dislike')

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]
    
    @property
    def like_count(self):
        return self.like_user_set.count()

    @property
    def dislike_count(self):
        return self.dislike_user_set.count()

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together =(('user', 'post'))

#싫어요 모델
class Dislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user', 'post'))
        

main/views.py
from django.shortcuts import get_list_or_404, render,redirect,get_object_or_404
from .models import Like, Post, Comment, Dislike
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# 2. 사용할 모듈 불러오기
# 2-1 POST 형식의 HTTP 통신만 받기
from django.views.decorators.http import require_POST
# 2-2 response를 변환하는 가장 가본 함수, html 파일, 이미지 등 다양한 응답
from django.http import HttpResponse
# 2-3 딕셔너리를 json 형식으로 바꾸기 위해
import json

# Create your views here.
def showmainpage(request):
    return render(request, 'main/mainpage.html')

def showintroduction(request):
    return render(request, 'main/introduction.html')

def showshow(request):
    return render(request, 'main/show.html' )

def showpost(request):
    posts = Post.objects.all()
    return render(request, 'main/post.html',{'posts':posts})

def detail(request,id):
    post = get_object_or_404(Post, pk = id)
    all_comments = post.comments.all().order_by('-created_at')
    return render(request, 'main/detail.html',{'post':post , 'comments':all_comments})

def new(request):
    return render(request, 'main/new.html')

def create(request):
    new_post = Post()
    new_post.title = request.POST['title']
    new_post.writer = request.user
    new_post.pub_date = timezone.now()
    new_post.body = request.POST['body']
    new_post.image = request.FILES.get('image')
    new_post.save()
    return redirect('main:detail',new_post.id)

def edit(request,id):
    edit_post = Post.objects.get(id = id)
    return render(request, 'main/edit.html', {'post' : edit_post})

def update(request, id):
    update_post = Post.objects.get(id = id)
    update_post.title = request.POST['title']
    update_post.writer = request.user
    update_post.pub_date = timezone.now()
    update_post.body = request.POST['body']
    update_post.image = request.FILES.get('image')
    update_post.save()
    return redirect('main:detail',update_post.id)

def delete(request, id):
    delete_post = Post.objects.get(id = id)
    delete_post.delete()
    return redirect("main:post")

def create_comment(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk = post_id)
        current_user = request.user
        comment_content = request.POST.get('content')
        Comment.objects.create(content = comment_content, writer=current_user, post=post)
    return redirect('main:detail', post_id)

def update_comment(request,comment_id):
    comment = get_object_or_404(Comment, pk = comment_id)
    post = Post.objects.get(id = comment.post.id)
    if request.method == "POST":
        post_id = comment.post.id
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('main:detail', post_id)
    return render(request, 'main/edit_comment.html',{"post":post,"comment": comment})

def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk = comment_id)
    post_id = comment.post.id
    comment.delete()
    return redirect("main:detail", post_id)

@require_POST
@login_required
def like_toggle(request,post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_like,post_like_created = Like.objects.get_or_create(user=request.user, post=post)
    post_dislike,post_dislike_created = Dislike.objects.get_or_create(user=request.user, post=post)

    if not post_like_created:
        post_like.delete()
        result = "like_cancel"
    else:
        result = "like"   

    context = {
        "like_count":post.like_count,
        "result": result,
    }
        
    return HttpResponse(json.dumps(context),content_type="application/json")

@require_POST
@login_required
def dislike_toggle(request,post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_dislike,post_dislike_created = Dislike.objects.get_or_create(user=request.user, post=post)

    if not post_dislike_created:
        post_dislike.delete()
        result = "dislike_cancel"
    else:
        result = "dislike"   

    context = {
        "dislike_count":post.dislike_count,
        "result": result,
    }
        
    return HttpResponse(json.dumps(context),content_type="application/json")

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <head>
      <link rel="stylesheet" href="{% static 'css/detail.css' %}?">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    </head>
    <body>
    {% include 'shared/_navbar.html' %}
    <h1>{{post.title}}</h1>  
    <div style="align-items: center;">
    <hr>
    </div>
    <table>
        <thead>
        <tr>
          <th scope="cols">항목</th>
          <th scope="cols">내용</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">작성자</th>
          {% if post.writer %}
          {% if 'user' in post.writer.username %}
          <td>{{post.writer.last_name}} {{post.writer.first_name}}</td>
          {% else %}
          <td>{{post.writer}}</td>
          {% endif %}
          {% else %}
          <td>알 수 없음</td>
          {% endif %}
        </tr>
        <tr>
          <th scope="row">날짜</th>
          <td>{{post.pub_date}}</td>
        </tr>
        <tr>
          <th scope="row">내용</th>
          <td>
            {% if post.image %}
            <p><img src="{{post.image.url}}" alt="사진"></p>
            {% endif %}
            <p>{{post.body}}</p>
          </td>
        </tr>
        <tr>
          <th>
            좋아요/싫어요  
          </th>
          <td>
            <div style="display: inline-block;">
            <span href="#" class="like" name ="{{post.id}}" value="Like"> 

              <!-- 만약 유저가 좋아요를 눌렀다면 채운 하트로 변경-->
              {% if user in post.like_user_set.all %}
                  <div class="alt-service-icon">
                      <i class="fas fa-thumbs-up" id ="like-icon" style="color:red;"></i>
                   </div> 
              <!-- 아니면 비워진 하트-->         
              {% else %}
          
                  <div class="alt-service-icon">
                       <i class="far fa-thumbs-up" id ="like-icon" style="color:red;"></i> 
                  </div>
          
               {% endif %}
          
               <span id="count1-{{ post.id }}" class="alt-services-title font-alt"> 
                  좋아요 
                  {% if post.like_count == 0 %} 
                    0개 
                  {% else %}
                      {{ post.like_count }}개
                  {% endif %}
               </span>
          </span>
          </div>
          &nbsp
          <div style="display: inline-block;">
          <span href="#" class="dislike" name ="{{post.id}}" value="dislike"> 

            <!-- 만약 유저가 싫어요를 눌렀다면 채운 하트로 변경-->
            {% if user in post.dislike_user_set.all %}
                <div class="alt-service-icon">
                  <i class="fas fa-thumbs-down" id ="dislike-icon" style="color:blue;"></i>
                 </div> 
            <!-- 아니면 비워진 하트-->         
            {% else %}
        
                <div class="alt-service-icon">
                     <i class="far fa-thumbs-down" id ="dislike-icon" style="color:blue;"></i> 
                </div>
        
             {% endif %}
        
             <span id="count2-{{ post.id }}" class="alt-services-title font-alt"> 
                싫어요 
                {% if post.dislike_count == 0 %} 
                  0개 
                {% else %}
                    {{ post.dislike_count }}개
                {% endif %}
             </span>
        </span>
        </div>
          </td>
        </tr>
        {% if user == post.writer %}
        <tr>
          <td class = "update" colspan="2" style="text-align: center;">
            <input type="button" value="수정하기" onclick="location.href='{% url 'main:edit' post.id %}'">
            <input type="button" value="삭제하기" onclick="location.href='{% url 'main:delete' post.id %}'">
          </td>
        </tr>
        {% endif %}
        </tbody>
      </table>
      <h1>댓글작성</h1>
      <div style="text-align: center;">
        <form action="{% url 'main:create_comment' post.id %}" method="POST">
          {%csrf_token%}
          <textarea name="content" placeholder="댓글 내용 입력" rows="3" cols="60"></textarea>
          <button type="submit" value="확인">댓글</button>
        </form>
      </div>
      <h1>댓글작성 목록</h1>
      <div style="text-align: center;">
        {% for comment in comments %}
        <div>
          {% if comment.writer %}
          {% if 'user' in comment.writer.username %}
          작성자 : {{ comment.writer.last_name }} {{ comment.writer.first_name }}
          {% else %}
          작성자 : {{ comment.writer }}
          {% endif %}
          {% else %}
          작성자 : 알 수 없음
          {% endif %}<br>
          {{comment.content}}<br>
          {% if user == comment.writer %}
          <button><a href="{% url 'main:update_comment' comment.id %}">댓글 수정</a></button>
			    <button><a href="{% url 'main:delete_comment' comment.id %}">댓글 삭제</a></button>
          {% endif %}
          <hr>
        </div>
        {% endfor %}
      </div>
    </body>
    <!-- 5. ajax 적용하기 -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".like").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            type:"POST",
            url:"{% url 'main:like_toggle' post.pk %}",
            data : {'pk':pk, 'csrfmiddlewaretoken':'{{csrf_token}}'},
            dataType:"json",
            success:function(response){
                if (response.like_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace("/account/login/");
                }
                else{
                    if (response.result == "like") {
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-thumbs-up');
                    }
                    else{
                        $('#like-icon').removeClass()
                        $('#like-icon').addClass('far fa-thumbs-up');
                    }
                    $('#count1-{{post.id}}').html('좋아요'+response.like_count+'개');
                }
            },
            error:function(request,status,error){
                alert("로그인이 필요합니다.")
                alert("code:"+response.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
            },
        })
    })
    $(".dislike").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            type:"POST",
            url:"{% url 'main:dislike_toggle' post.pk %}",
            data : {'pk':pk, 'csrfmiddlewaretoken':'{{csrf_token}}'},
            dataType:"json",
            success:function(response){
                if (response.dislike_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace("/account/login/");
                }
                else{
                    if (response.result == "dislike") {
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('fas fa-thumbs-down');
                    }
                    else{
                        $('#dislike-icon').removeClass()
                        $('#dislike-icon').addClass('far fa-thumbs-down');
                    }
                    $('#count2-{{post.id}}').html('싫어요'+response.dislike_count+'개');
                }
            },
            error:function(request,status,error){
                alert("로그인이 필요합니다.")
                alert("code:"+response.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
            },
        })
    })
</script>

{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <head>
      <link rel="stylesheet" href="{%static 'css/new.css'%}">
    </head>
    <body>
        {% include 'shared/_navbar.html'%}
        <div>
            <div id = "write">글쓰기</div>
            <img src="{%static 'image/pencil.png'%}" width= "40" height="40" style="margin-bottom: 25px; display: inline-block;">
        </div>
        <hr>
        <table>
            <thead>
            <tr>
              <th scope="cols">항목</th>
              <th scope="cols">내용</th>
            </tr>
            </thead>
            <tbody>
            <form action="{%url 'main:update' post.id%}" method="post" enctype="multipart/form-data">
                {%csrf_token%}
            <tr>
              <th scope="row">제목</th>
              <td><input type="text" name="title" value="{{post.title}}"></td>
            </tr>
            <tr>
              <th scope="row">사진</th>
              <td><input type="file" name = "image" value=></td>
            </tr>
            <tr>
              <th scope="row">내용</th>
              <td><textarea type="text" name="body" id="" cols="100" rows="10">{{post.body}}</textarea></td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;"><button type="submit">제출</button></td>
            </tr>
            </tbody>
          </table>         
    </body>
{% endblock %}

main/templates/main/edit_comment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <head>
      <link rel="stylesheet" href="{%static 'css/detail.css' %}">
    </head>
    <body>
    {% include 'shared/_navbar.html' %}
    <h1>{{post.title}}</h1>  
    <hr>
    <table>
        <thead>
        <tr>
          <th scope="cols">항목</th>
          <th scope="cols">내용</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">작성자</th>
          {% if post.writer %}
          {% if 'user' in post.writer.username %}
          <td>{{post.writer.last_name}} {{post.writer.first_name}}</td>
          {% else %}
          <td>{{post.writer}}</td>
          {% endif %}
          {% else %}
          <td>알 수 없음</td>
          {% endif %}
        </tr>
        <tr>
          <th scope="row">날짜</th>
          <td>{{post.pub_date}}</td>
        </tr>
        <tr>
          <th scope="row">내용</th>
          <td>
            {% if post.image %}
            <p><img src="{{post.image.url}}" alt="사진"></p>
            {% endif %}
            <p>{{post.body}}</p>
          </td>
        </tr>
        </tbody>
      </table>
      <h1>댓글수정</h1>
      <div style="text-align: center;">
        <form action="{% url 'main:update_comment' comment.id %}" method="POST">
          {%csrf_token%}
          <textarea name="content" placeholder="댓글 내용 입력" rows="3" cols="60">{{comment.content}}</textarea>
          <button type="submit" value="댓글 수정">댓글수정</button>
        </form>
      </div>
    </body>
{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
  <link rel="stylesheet" href="{% static 'css/mainpage.css' %}">
</head>
<body style="background-color: black;">
    {% include 'shared/_navbar.html' %}
    <div style="margin-top: 5%;">
      <P style="color: white; text-align: center;">멋쟁이 사자처럼 9기</p>
      <P style="color: white; text-align: center;">자기소개 홈페이지 만들기</p>
    </div>
    <img id ="logo" src ="{% static 'image/멋사로고.png' %}">
</body>
{% endblock %}

main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <head>
      <link rel="stylesheet" href="{%static 'css/new.css'%}">
    </head>
    <body>
        {% include 'shared/_navbar.html'%}
        <div>
            <div id = "write">글쓰기</div>
            <img src="{%static 'image/pencil.png'%}" width= "40" height="40" style="margin-bottom: 25px; display: inline-block;">
        </div>
        <hr>
        <table>
            <thead>
            <tr>
              <th scope="cols">항목</th>
              <th scope="cols">내용</th>
            </tr>
            </thead>
            <tbody>
            <form action="{%url 'main:create'%}" method="post" enctype="multipart/form-data">
                {%csrf_token%}
            <tr>
              <th scope="row">제목</th>
              <td><input type="text" name="title"></td>
            </tr>
            <tr>
              <th scope="row">사진</th>
              <td><input type="file" name = "image"></td>
            </tr>
            <tr>
              <th scope="row">내용</th>
              <td><textarea type="text" name="body" id="" cols="100" rows="10"></textarea></td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center;"><button type="submit">제출</button></td>
            </tr>
            </tbody>
          </table>         
    </body>
{% endblock %}

main/templates/main/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
  <link rel="stylesheet" href="{%static 'css/post.css'%}">
</head>
<body>
    {% include 'shared/_navbar.html' %}
    {% if user.is_authenticated %}
    <div class='write title'>
      <img src="{%static 'image/letter.png' %}" width="100px" height="100px" style="margin-bottom: 20px;">
      <P>방문자 글쓰기</p>
    </div>
    <div class="write" style="margin-left: 55%;">
        <input type="button" value="글쓰기" onclick="location.href='{%url 'main:new'%}'">
    </div>   
    <table class="profile" style=" width: 60%;">
        <thead>
        <tr>
          <th scope="cols" width=10%>순번</th>
          <th scope="cols" width=40%>제목</th>
          <th scope="cols" width=15%>작성자</th>
          <th scope="cols" width=35%>날짜</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %} 
        <tr onclick="location.href='{% url 'main:detail' post.id %}'">
            <td>{{ forloop.counter }}</td>
            <td>{{ post.title }}</td>
            {% if post.writer %}
            {% if 'user' in post.writer.username and post.writer.username != 'user' %}
            <td><a href="{% url 'users:mypage' post.writer.id %}">{{post.writer.last_name}} {{post.writer.first_name}}</a></td>
            {% else %}
            <td><a href="{% url 'users:mypage' post.writer.id %}">{{post.writer}}</a></td>
            {% endif %}
            {% else %}
            <td>알 수 없음</td>
            {% endif %}
            <td>{{ post.pub_date }}</td>  
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="account" style="text-align: center;margin: 100px 0px;">
        <h1>로그인 후 이용가능</h1><br>
        <a style="text-decoration: none; color: black;" href="{% url 'account_login' %}"><button>로그인</button></a><br>
        <a style="text-decoration: none; color:black;" href="{% url 'account_signup' %}"><button>회원가입</button></a>
    </div>    
    {% endif %}
</body>
<style>
    table {
    border-collapse: collapse;
    text-align: left;
    line-height: 1.5;
    border-left: 1px solid #ccc;
    margin: auto;
  }
  
  table thead th {
    padding: 10px;
    font-weight: bold;
    border-top: 1px solid #ccc;
    border-right: 1px solid #ccc;
    border-bottom: 2px solid #c00;
    background: #dcdcd1;
  }
  table tbody th {
    width: 150px;
    padding: 10px;
    font-weight: bold;
    vertical-align: top;
    border-right: 1px solid #ccc;
    border-bottom: 1px solid #ccc;
    background: #ececec;
  }
  table td {
    width: 350px;
    padding: 10px;
    vertical-align: top;
    border-right: 1px solid #ccc;
    border-bottom: 1px solid #ccc;
    background: white;
  }
</style>
{% endblock %}

main/templates/main/show.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/show.css' %}">
</head>
<body>
    {% include 'shared/_navbar.html' %}
    <table style="height: 100%;">
        <td style="width: 40%;"> 
            <div id="main">
                <h1>
                    <div class="title" style="margin-top: 10px; margin-bottom: 30px;">오늘 요리는</div>
                    <div class="point" style="color:black;">쉽게</div>
                    <div class="point"style="color:black;">맛있게</div>
                    <div class="point"style="color:black;">간단하게</div>
                </h1>
                    <p>집에 있는 재료들로<br>
                        알차게 한끼식사를 해결하자</p>
                <div id = "circle-wrapper">
                    <div class="circle1"><img id="stake" src ="{% static 'image/스테이크.jpeg' %}"></div>
                    <div class="circle2"><img id="kimchi" src="{% static 'image/김치.jpg' %}"></div>
                    <div class="circle3"><img id="giblet" src="{% static 'image/곱창.jpg' %}"></div>
                </div>
                <div id ="badge" style="left: 30%; top:120px;">
                    <img src="{% static 'image/dish.png' %}" width="50px" height="50px">
                </div>
            </div>
        </td>
        <td style="width:60%; text-align: center;">
            <div style="font-size: 50px; color:rgb(219, 123, 33);"><span style="color: black;"><</span>오늘의 요리는<span style="color: black;">></span></div>
            <div style="padding-left: 5%; padding-right: 5%; line-height: 5em;" >
                <p>'오늘의 요리'는 제가 멋쟁이사자처럼 9기 지원서에 쓴 구현하고 싶은 서비스로 현재 1인가구의 비율이 늘고 있는 상황과 배달 음식의 경우
                    2~3인분을 시켜야 하는 상황에서 집에 있는 재료들을 가지고 만들 수 있는 음식 레시피를 보여주는 서비스 입니다. 작동방식은 재료들을 선택하면
                    그 재료들로 만들 수 있는 음식 레시피를 제공해주는 것입니다. 아직은 메인 화면만 구상하고 
                    있어서 다음과 같은 디자인(모바일용)으로 생각했고 앞으로 모바일과 웹 둘다 완성해나가는 것이 목표입니다. 
                </p>
            </div>
        </td> 
    </table>
</body>
{% endblock %}