main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', showmainpage, name="mainpage"),
    path('main/', showmainpage, name="mainpage"),
    path('introduction/',showintroduction, name="introduction"),
    path('show/',showshow, name="show"),
    path('post/',showpost, name="post"),
    path('<int:id>',detail, name="detail"),
    path('new/', new, name="new"),
    path('create/',create, name="create"),
    path('edit/<int:id>',edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<int:post_id>/create_comment',create_comment,name="create_comment"),
    path('<int:comment_id>/update_comment',update_comment,name="update_comment"),
    path('<int:comment_id>/delete_comment',delete_comment, name="delete_comment"),

    path('like_toggle/<int:post_id>/',like_toggle,name="like_toggle"),
    path('dislike_toggle/<int:post_id>/',dislike_toggle,name="dislike_toggle"),
]

sns_project/sns_project/urls.py
from django.contrib import admin
from django.urls import path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.showbase, name="showbase"),
    path('mainpage/',views.showmainpage, name="mainpage"),
    path('show/',views.showshow, name="show"),
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .import views

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage',views.mypage, name="mypage"),
    path('<int:id>/follow',views.follow, name="follow"),
]

sns_project/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">동국대 멋쟁이사자처럼</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:mainpage' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:introduction' %}">자기소개홈페이지</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:show' %}">만들고 싶은 서비스</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:post' %}">방문자 글쓰기</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown"  style="position: absolute; right: 17%;">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              팔로워
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="nav-item">팔로워 : {{request.user.profile.followers.count}} 명 </li>
              {%for follower in request.user.profile.followers.all %}
              {% if follower.user.username == "user" %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:mypage' follower.user.id %}">
                  {{follower.user.last_name}} {{follower.user.first_name}}
                  </a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:mypage' follower.user.id %}">
                    {{follower.user.username}}
                  </a>
                </li>  
                {% endif %}
                {% endfor %}
            </ul>
          </li>
          <li class="nav-item dropdown"  style="position: absolute; right: 12%;">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              팔로잉
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="nav-item">팔로잉 : {{request.user.profile.followings.count}} 명 </li>
              {%for following in request.user.profile.followings.all %}
              {% if following.user.username == "user" %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:mypage' following.user.id %}">
                  {{following.user.last_name}} {{following.user.first_name}}
                  </a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:mypage' following.user.id %}">
                    {{following.user.username}}
                  </a>
                </li>  
                {% endif %}
                {% endfor %}
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">로그인</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">회원가입</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item dropdown" style="position: absolute; right: 5%;">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {% if request.user.username == "user" %}
              {{request.user.last_name}} {{request.user.first_name}}
              {% else %}
              {{request.user.username}}
              {% endif %}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:mypage' request.user.id %}">마이페이지</a>
              </li>
            </ul>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>